$ErrorActionPreference = 'Stop'

$now = Get-Date
$year = $now.Year
$month = $now.Month
$day = $now.Day
$minuteOfDay = $now.Hour * 60 + $now.Minute

$monthPadded = $month.ToString('00')
$dayPadded = $day.ToString('00')
$minutePadded = $minuteOfDay.ToString('0000')

$versionString = '{0}.{1}.{2}.{3}' -f $year, $monthPadded, $dayPadded, $minutePadded

$headerPath = Join-Path $PSScriptRoot '..\autoversion.h'
$rcPath = Join-Path $PSScriptRoot '..\autoversion.rc'

$headerContent = @"
#pragma once
// Auto-generated by scripts/gen-version.ps1 at build time
// Do not edit manually.

#include "nexus/Nexus.h"

inline void SeedAddonVersionFromBuild(AddonDefinition& def)
{
    def.Version.Major = $year;
    def.Version.Minor = $month;
    def.Version.Build = $day;
    def.Version.Revision = $minuteOfDay;
}
"@

$currentHeader = if (Test-Path $headerPath) { Get-Content -Raw -Path $headerPath } else { '' }
if ($currentHeader -ne $headerContent) {
    Set-Content -Path $headerPath -Value $headerContent -Encoding ASCII
}

$rcContent = @"
#include <windows.h>
#include <winver.h>

VS_VERSION_INFO VERSIONINFO
 FILEVERSION $year,$month,$day,$minuteOfDay
 PRODUCTVERSION $year,$month,$day,$minuteOfDay
 FILEFLAGSMASK VS_FFI_FILEFLAGSMASK
 FILEFLAGS 0x0L
 FILEOS VOS_NT_WINDOWS32
 FILETYPE VFT_DLL
 FILESUBTYPE VFT2_UNKNOWN
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904E4"
        BEGIN
            VALUE "FileDescription", "WvW Fight Analysis"
            VALUE "FileVersion", "$versionString"
            VALUE "InternalName", "WvW Fight Analysis"
            VALUE "OriginalFilename", "WvWFightAnalysis.dll"
            VALUE "ProductName", "WvW Fight Analysis"
            VALUE "ProductVersion", "$versionString"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x0409, 1252
    END
END
"@

$currentRc = if (Test-Path $rcPath) { Get-Content -Raw -Path $rcPath } else { '' }
if ($currentRc -ne $rcContent) {
    Set-Content -Path $rcPath -Value $rcContent -Encoding ASCII
}

Write-Host "Generated autoversion.{h,rc} with $versionString"
