#pragma once
// Auto-generated by scripts/gen-version.ps1 at build time
// Do not edit manually.

#include "nexus/Nexus.h"

inline void SeedAddonVersionFromBuild(AddonDefinition& def)
{
    def.Version.Major = 2025;
    def.Version.Minor = 10;
    def.Version.Build = 31;
    def.Version.Revision = 1322;
}
