#pragma once
// Auto-generated by scripts/gen-version.ps1 at build time
// Do not edit manually.

#include "nexus/Nexus.h"

inline void SeedAddonVersionFromBuild(AddonDefinition& def)
{
    def.Version.Major = 2026;
    def.Version.Minor = 6;
    def.Version.Build = 19;
    def.Version.Revision = 989;
}
