//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
//
#define BERSERKER                       101
#define BLADESWORN                      102
#define CATALYST                        103
#define CHRONOMANCER                    104
#define DAREDEVIL                       105
#define DEADEYE                         106
#define DRAGONHUNTER                    107
#define DRUID                           108
#define ELEMENTALIST                    109
#define ENGINEER                        110
#define FIREBRAND                       111
#define GUARDIAN                        112
#define HARBINGER                       113
#define HERALD                          114
#define HOLOSMITH                       115
#define MECHANIST                       116
#define MESMER                          117
#define MIRAGE                          118
#define NECROMANCER                     119
#define RANGER                          120
#define REAPER                          121
#define REVENANT                        122
#define RENEGADE                        123
#define SCRAPPER                        124
#define SCRAPPER_WHITE                  161
#define SCRAPPER_SIMPLE                 162
#define SCRAPPER_SIMPLE_WHITE           163
#define BERSERKER_WHITE                200
#define BERSERKER_SIMPLE               201
#define BERSERKER_SIMPLE_WHITE         202
#define BLADESWORN_WHITE               203
#define BLADESWORN_SIMPLE              204
#define BLADESWORN_SIMPLE_WHITE        205
#define CATALYST_WHITE                 206
#define CATALYST_SIMPLE                207
#define CATALYST_SIMPLE_WHITE          208
#define CHRONOMANCER_WHITE             209
#define CHRONOMANCER_SIMPLE            210
#define CHRONOMANCER_SIMPLE_WHITE      211
#define DAREDEVIL_WHITE                212
#define DAREDEVIL_SIMPLE               213
#define DAREDEVIL_SIMPLE_WHITE         214
#define DEADEYE_WHITE                  215
#define DEADEYE_SIMPLE                 216
#define DEADEYE_SIMPLE_WHITE           217
#define DRAGONHUNTER_WHITE             218
#define DRAGONHUNTER_SIMPLE            219
#define DRAGONHUNTER_SIMPLE_WHITE      220
#define DRUID_WHITE                    221
#define DRUID_SIMPLE                   222
#define DRUID_SIMPLE_WHITE             223
#define ELEMENTALIST_WHITE             224
#define ELEMENTALIST_SIMPLE            225
#define ELEMENTALIST_SIMPLE_WHITE      226
#define ENGINEER_WHITE                 227
#define ENGINEER_SIMPLE                228
#define ENGINEER_SIMPLE_WHITE          229
#define FIREBRAND_WHITE                230
#define FIREBRAND_SIMPLE               231
#define FIREBRAND_SIMPLE_WHITE         232
#define GUARDIAN_WHITE                 233
#define GUARDIAN_SIMPLE                234
#define GUARDIAN_SIMPLE_WHITE          235
#define HARBINGER_WHITE                236
#define HARBINGER_SIMPLE               237
#define HARBINGER_SIMPLE_WHITE         238
#define HERALD_WHITE                   239
#define HERALD_SIMPLE                  240
#define HERALD_SIMPLE_WHITE            241
#define HOLOSMITH_WHITE                242
#define HOLOSMITH_SIMPLE               243
#define HOLOSMITH_SIMPLE_WHITE         244
#define MECHANIST_WHITE                245
#define MECHANIST_SIMPLE               246
#define MECHANIST_SIMPLE_WHITE         247
#define MESMER_WHITE                   248
#define MESMER_SIMPLE                  249
#define MESMER_SIMPLE_WHITE            250
#define MIRAGE_WHITE                   251
#define MIRAGE_SIMPLE                  252
#define MIRAGE_SIMPLE_WHITE            253
#define NECROMANCER_WHITE              254
#define NECROMANCER_SIMPLE             255
#define NECROMANCER_SIMPLE_WHITE       256
#define RANGER_WHITE                   257
#define RANGER_SIMPLE                  258
#define RANGER_SIMPLE_WHITE            259
#define REAPER_WHITE                   260
#define REAPER_SIMPLE                  261
#define REAPER_SIMPLE_WHITE            262
#define RENEGADE_WHITE                 263
#define RENEGADE_SIMPLE                264
#define RENEGADE_SIMPLE_WHITE          265
#define REVENANT_WHITE                 266
#define REVENANT_SIMPLE                267
#define REVENANT_SIMPLE_WHITE          268
#define SCOURGE_WHITE                  269
#define SCOURGE_SIMPLE                 270
#define SCOURGE_SIMPLE_WHITE           271
#define SOULBEAST_WHITE                272
#define SOULBEAST_SIMPLE               273
#define SOULBEAST_SIMPLE_WHITE         274
#define SPECTER_WHITE                  275
#define SPECTER_SIMPLE                 276
#define SPECTER_SIMPLE_WHITE           277
#define SPELLBREAKER_WHITE             278
#define SPELLBREAKER_SIMPLE            279
#define SPELLBREAKER_SIMPLE_WHITE      280
#define TEMPEST_WHITE                  281
#define TEMPEST_SIMPLE                 282
#define TEMPEST_SIMPLE_WHITE           283
#define THIEF_WHITE                    284
#define THIEF_SIMPLE                   285
#define THIEF_SIMPLE_WHITE             286
#define UNTAMED_WHITE                  287
#define UNTAMED_SIMPLE                 288
#define UNTAMED_SIMPLE_WHITE           289
#define VINDICATOR_WHITE               290
#define VINDICATOR_SIMPLE              291
#define VINDICATOR_SIMPLE_WHITE        292
#define VIRTUOSO_WHITE                 293
#define VIRTUOSO_SIMPLE                294
#define VIRTUOSO_SIMPLE_WHITE          295
#define WARRIOR_WHITE                  296
#define WARRIOR_SIMPLE                 297
#define WARRIOR_SIMPLE_WHITE           298
#define WEAVER_WHITE                   299
#define WEAVER_SIMPLE                  300
#define WEAVER_SIMPLE_WHITE            301
#define WILLBENDER_WHITE               302
#define WILLBENDER_SIMPLE              303
#define WILLBENDER_SIMPLE_WHITE        304
#define AMALGAM_WHITE                  305
#define AMALGAM_SIMPLE                 306
#define AMALGAM_SIMPLE_WHITE           307
#define ANTIQUARY_WHITE                308
#define ANTIQUARY_SIMPLE               309
#define ANTIQUARY_SIMPLE_WHITE         310
#define CONDUIT_WHITE                  311
#define CONDUIT_SIMPLE                 312
#define CONDUIT_SIMPLE_WHITE           313
#define EVOKER_WHITE                   314
#define EVOKER_SIMPLE                  315
#define EVOKER_SIMPLE_WHITE            316
#define GALESHOT_WHITE                 317
#define GALESHOT_SIMPLE                318
#define GALESHOT_SIMPLE_WHITE          319
#define LUMINARY_WHITE                 320
#define LUMINARY_SIMPLE                321
#define LUMINARY_SIMPLE_WHITE          322
#define PARAGON_WHITE                  323
#define PARAGON_SIMPLE                 324
#define PARAGON_SIMPLE_WHITE           325
#define RITUALIST_WHITE                326
#define RITUALIST_SIMPLE               327
#define RITUALIST_SIMPLE_WHITE         328
#define TROUBADOUR_WHITE               329
#define TROUBADOUR_SIMPLE              330
#define TROUBADOUR_SIMPLE_WHITE        331
#define SCOURGE                         125
#define SOULBEAST                       126
#define SPECTER                         127
#define SPELLBREAKER                    128
#define TEMPEST                         129
#define THIEF                           130
#define UNTAMED                         131
#define VINDICATOR                      132
#define VIRTUOSO                        133
#define WARRIOR                         134
#define WEAVER                          135
#define WILLBENDER                      136
#define AMALGAM                         152
#define ANTIQUARY                       153
#define CONDUIT                         154
#define EVOKER                          155
#define GALESHOT                        156
#define LUMINARY                        157
#define PARAGON                         158
#define RITUALIST                       159
#define TROUBADOUR                      160
#define DEATH                           137
#define DOWNED                          138
#define SQUAD                           139
#define DAMAGE                          140
#define CONDI                           141
#define STRIKE                          142
#define KDR                             143
#define HOME                            144
#define DOWNCONT                        145
#define KILLCONT                        146
#define STRIPS                          147
#define PIE_BACKGROUND                  148
#define PIE_GLOBE                       149
#define PIE_SEPARATOR                   150
#define MENOMONIA_SANS_FONT             151

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        332
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

